forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, IntegerField, DateField, BooleanField, RadioField
from wtforms.validators import DataRequired, Email, Length
from wtforms.fields.html5 import EmailField

class frmRegistrar(FlaskForm):
    identificacion = IntegerField("identificacion", validators=[
        DataRequired()
    ])
    nombre = StringField("Nombre", validators=[
        DataRequired(),
        Length(max=10, min=3)
    ])
    apellidos = StringField("Apellidos", validators=[
        DataRequired(),
        Length(max=30, min=3)
    ])
    fechaNacimiento = DateField(
        "Fecha de Nacimiento",
        format = '%d/%m/%y'
    )
    genero = RadioField("Genero", choices=[('M','Masculino'),('F','Femenino'),('O','Otro')], validators=[
        DataRequired()
    ])
    telefono = IntegerField("Telefono")
    correo = EmailField("Correo", validators=[
        DataRequired(),
        Email()
    ])
    contraseña = PasswordField("Contraseña", validators=[
        DataRequired()
    ])
    condiciones = BooleanField("")
    registrar = SubmitField("Registrar")

class frmLogin(FlaskForm):
    correo = EmailField("E-mail", validators=[
        DataRequired(),
        Email()
    ])
    contraseña = PasswordField("Contraseña", validators=[
        DataRequired()
    ])
    iniciarsesion = SubmitField("Iniciar Sesion")

class frmRecordarContraseña(FlaskForm):
    dato = StringField("Dato de Identificación:", validators=[
        DataRequired()
    ])
    newContraseña = PasswordField("Nueva Contraseña", validators=[
        DataRequired()
    ])
    newContraseña2 = PasswordField("Confirmar Contraseña", validators=[
        DataRequired()
    ])
    enviar = SubmitField("Enviar")

app.py
import os
from flask import Flask
# from flask_bootstrap import Bootstrap

def create_app():

    app = Flask(__name__)
    app.secret_key = os.urandom( 50 )

    from views import main

    # Bootstrap(app)
    app.register_blueprint(main)

    return app

views.py
from flask import blueprints, render_template, request, url_for, redirect
from forms import frmRegistrar, frmLogin, frmRecordarContraseña
import re

main=blueprints.Blueprint('main', __name__)

@main.route('/', methods=["GET"])
def index():
    return render_template('Inicio.html')


@main.route('/login', methods=["GET"])
@main.route('/login/<tipo>', methods=["GET", "POST"])
def login(tipo):
    x = frmLogin()
    
    if request.method == 'POST':
        return render_template("main.dashboard", tipo=tipo)
        
    return render_template('Login-wtf.html', tipo=tipo, form=x)
    

@main.route('/dashboard', methods=["GET", "POST"])
@main.route('/dashboard/<tipo>', methods=["GET", "POST"])
def dashboard(tipo=None):
    if tipo == None:
        return redirect('/login/piloto')
    
    return render_template('Dashboard.html', tipo=tipo)


@main.route('/consultavuelo', methods=["GET", "POST"])
@main.route('/consultavuelo/<tipo>', methods=["GET", "POST"])
def consultaVuelo(tipo=None):
    if tipo == None:
        return redirect('/login/piloto')

    return render_template('Consultar.html', tipo=tipo)


@main.route('/calificaVuelo', methods=["GET", "POST"])
@main.route('/calificavuelo/<tipo>', methods=["GET", "POST"])
def calificaVuelo(tipo=None):
    if tipo == None:
        return redirect('/login/Usuario')
        
    return render_template('Calificanos.html', tipo=tipo)


@main.route('/reservaVuelo', methods=["GET", "POST"])
@main.route('/reservaVuelo/<tipo>', methods=["GET", "POST"])
def reservaVuelo(tipo=None):
    if tipo == None:
        return redirect('/login/Usuario')
        
    return render_template('Reservar.html', tipo=tipo)


@main.route('/registro', methods=["GET", "POST"])
def registro():
    x = frmRegistrar()    
    return render_template('Registro-wtf.html', form=x)


@main.route('/restaurar_contraseña', methods=["GET"])
def restaurar_contraseña():
    x = frmRecordarContraseña()
    return render_template('RestablecerContraseña-wtf.html', form=x)


def validar_contraseña(password):
    if len(password) >= 8:
        if re.search('[a-z]', password) and re.search('[A-Z]', password):
            if re.search('[0-9]', password):
                if re.search('[$@#]', password):
                    return True;

    return False;

templates/Calificanos.html
<!DOCTYPE html>
<html lang="sp">
<head>
<META charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('static', filename='CSS/mioCSS.css') }}" />
<link rel="stylesheet" type="text/css" media="print"  href="{{ url_for('static', filename='CSS/print.css') }}" />

<script src="https://kit.fontawesome.com/d42f451a54.js" crossorigin="anonymous"></script>

<title>Califica tu vuelo</title>

<link rel="shortcut icon" type="image/png" href="img/favicon.png"/>
</head>
<body>
  <a href="{{ url_for('main.index') }}" method="GET">
    <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
  </a>

  <div class="menu">
    <a href="{{ url_for('main.dashboard', tipo=tipo) }}">
    {% if tipo == "Admin" %}
        Agregar Vuelo
    {% else %}
        Dashboard {{ tipo }}</a>
    {% endif %}
    <a href="{{ url_for('main.consultaVuelo', tipo=tipo) }}">Consultar</a>
    
    {% if tipo == "Usuario" %}
      <a href="{{ url_for('main.reservaVuelo', tipo=tipo) }}">Reservar</a>
      <a href="{{ url_for('main.calificaVuelo', tipo=tipo) }}">Calificanos</a>
    {% endif %}
    
    <a href="{{ url_for('main.index') }}">Cerrar Sesion</a>
  </div>

  <div class="publicacion">
    <h3 class="caja">CALIFICANOS</h3>

    <wrapper div id='wrapper'>
      <form action='' class='form'>
        <p class='field required half'>
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' placeholder="Ingresa el codigo de tu vuelo" required type='text'>
        </p>
        
        <p class='field'>
          <input class='button' type='submit' value='Consultar'>
        </p>
        
        <p class='field required half'>Código
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Código' required type='text'>
        </p>
        
        <p class='field required half'>Avión
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Avión' required type='text'>
        </p>
        
        <p align="center">
        <p class='field required half'>Piloto
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Piloto' required type='text'>
        </p>
        
        <p class='field required half'>Estado
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Estado' required type='text'>
        </p>
        
        <div class="txt-center">
          <p class='field'>Calificación y comentarios
            <label class='label' for='message'></label>
            <textarea class='textarea' cols='50' id='message' name='message' required rows='4'></textarea>
          </p>
   
          <p class='field'>
            <input class='button' type='submit' value='Enviar calificación'>
          </p>
        </div>
   
      </form>
    </wrapper>
  </div>
</body>
</html>

templates/Consultar.html
<!DOCTYPE html>
<html lang="sp">
<head>
<META charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('static', filename='CSS/mioCSS.css') }}" />
<link rel="stylesheet" type="text/css" media="print"  href="{{ url_for('static', filename='CSS/print.css') }}" />

<script src="https://kit.fontawesome.com/d42f451a54.js" crossorigin="anonymous"></script>
<title>Consulta tu vuelo</title>

<link rel="shortcut icon" type="image/png" href="img/favicon.png"/>
</head>
<body>
  <a href="{{ url_for('main.index') }}" method="GET">
    <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
  </a>

  <div class="menu">
    <a href="{{ url_for('main.dashboard', tipo=tipo) }}">
    {% if tipo == "Admin" %}
        Agregar Vuelo
    {% else %}
        Dashboard {{ tipo }}</a>
    {% endif %}
    <a href="{{ url_for('main.consultaVuelo', tipo=tipo) }}">Consultar</a>

    {% if tipo == "Usuario" %}
      <a href="{{ url_for('main.reservaVuelo', tipo=tipo) }}">Reservar</a>
      <a href="{{ url_for('main.calificaVuelo', tipo=tipo) }}">Calificanos</a>
    {% endif %}
    
    <a href="{{ url_for('main.index') }}">Cerrar Sesion</a>
  </div>

  <div class="publicacion">
    <h3 class="caja">CONSULTA TU VUELO</h3>

    <wrapper div id='wrapper'>
      <form action='' class='form'>
        <p class='field required half'>
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' placeholder="Ingresa el codigo de tu vuelo" required type='text'>
        </p>

        <p class='field'>
          <input class='button' type='submit' value='Consultar'>
        </p>
        
        <p class='field required half'>Código
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' required type='text'>
        </p>
        
        <p class='field required half'>Avión
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' required type='text'>
        </p>
        <p align="center">
        <p class='field required half'>Piloto
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' required type='text'>
        </p>
        <p class='field required half'>Capacidad
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' required type='text'>
        </p>
        <p align="center">
        <p class='field required half'>Estado
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' required type='text'>
        </p></p>

        {% block content %}
        {% if tipo == "Admin" %}
          <p class='field'>
            <input class='button' type='submit' value='Editar'>
        
            <input class='button' type='submit' value='Eliminar'>
          </p>
        {% endif %}
        {% endblock content %}

      </form>
    </wrapper>
  </div>
</body>
</html>

templates/Dashboard.html
<!DOCTYPE html>
<html lang="sp">
<head>
<META charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('static', filename='CSS/mioCSS.css') }}" />
<link rel="stylesheet" type="text/css" media="print"  href="{{ url_for('static', filename='CSS/print.css') }}" />

<script src="https://kit.fontawesome.com/d42f451a54.js" crossorigin="anonymous"></script>
        
<title>Dashboard {{ tipo }}</title>

<link rel="shortcut icon" type="image/png" href="img/favicon.png"/>
</head>
<body>
    <a href="{{ url_for('main.index') }}" method="GET">
        <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
    </a>

    <div class="menu">
        <a href="{{ url_for('main.dashboard', tipo=tipo) }}">
        {% if tipo == "Admin" %}
            Agregar Vuelo
        {% else %}
            Dashboard {{ tipo }}</a>
        {% endif %}
        <a href="{{ url_for('main.consultaVuelo', tipo=tipo) }}">Consultar</a>

        
        {% if tipo == "Usuario" %}
            <a href="{{ url_for('main.reservaVuelo', tipo=tipo) }}">Reservar</a>
            <a href="{{ url_for('main.calificaVuelo', tipo=tipo) }}">Calificanos</a>
        {% endif %}
        
        <a href="{{ url_for('main.index') }}">Cerrar Sesion</a>
      </div>
    
    <div>
        {% block content %}
        {% if tipo == "Usuario" %}
            <div id="cpestana1">
                
                <select class="select">
                    <option disabled="">Selecciona el usuario</option>
                    <option value="Nancy Castellanos Torres">Nancy Castellanos Torres</option>
                    <option value="Fabian Beltran Bustos">Fabian Beltran Busto</option>
                    <option value="Heygler Garcia Castro">Heygler Garcia Castro</option>
                    <option value="Yezid Martinez Gomez">Yezid Martinez Gomez</option>
                </select> 
                
                <form  class='form'>
                    <input class="text-input" type="text" id="nombre" name="nombre" placeholder="Nombre"/><br><br>
                    <input class="text-input" type="text" id="apellido" name="apellido" placeholder="Apellidos"/><br><br> 
                    <input class="text-input" type="text" id="cedula" name="cedula" placeholder="Cedula"/><br><br> 
                    <input class="text-input" type="text" id="edad" name="edad" placeholder="Edad"/><br><br> 
                    <input class="text-input" type="text" id="correo" name="correo" placeholder="Correo"/><br><br>
                    <input class="text-input" type="text" id="telefono" name="telefono" placeholder="Telefono" /><br><br> 
                    <input class="text-input" type="text" id="direccion" name="direccion" placeholder="Direccion"/><br><br>                       
                    
                    <select class="select">
                        <option disabled="">Vuelos reservados</option>
                        <option value="Santa Marta">Santa Marta</option>
                        <option value="Bogota">Bogota</option>
                        <option value="Medellin">Medellin</option>
                        <option value="Pereira">Pereira</option>
                    </select> 
                    
                    <br><br><br><br><br><br>
                    <a class="button" href="https://www.google.com">EDITAR</a>
                </form>
                
            </div>

        {% elif tipo == "Piloto" %}
            <div id="cpestana2">
                            
                <select class="select">
                    <option disabled="">Selecciona el piloto</option>
                    <option value="Nancy Castellanos Torres">Nancy Castellanos Torres</option>
                    <option value="Fabian Beltran Bustos">Fabian Beltran Busto</option>
                    <option value="Heygler Garcia Castro">Heygler Garcia Castro</option>
                    <option value="Yezid Martinez Gomez">Yezid Martinez Gomez</option>
                </select> 
                
                <form  class='form'>
                    <input class="text-input" type="text" id="nombre" name="nombre" placeholder="Nombre"/><br><br>
                    <input class="text-input" type="text" id="apellido" name="apellido" placeholder="Apellidos"/><br><br> 
                    <input class="text-input" type="text" id="cedula" name="cedula" placeholder="Cedula"/><br><br> 
                    <input class="text-input" type="text" id="edad" name="edad" placeholder="Edad"/><br><br> 
                    <input class="text-input" type="text" id="correo" name="correo" placeholder="Correo"/><br><br>
                    <input class="text-input" type="text" id="telefono" name="telefono" placeholder="Telefono" /><br><br> 
                    <input class="text-input" type="text" id="direccion" name="direccion" placeholder="Direccion"/><br><br> 
                    <input class="text-input" type="text" id="origen" name="origen" placeholder="Origen"/><br><br> 
                    <input class="text-input" type="text" id="destino" name="destino" placeholder="Destino"/><br><br> 
                    <input class="text-input" type="text" id="hora" name="hora" placeholder="Hora"/><br><br> 
                    <input class="text-input" type="text" id="avion" name="avion" placeholder="Avion"/><br><br> 
                    
                    <select class="select">
                        <option disabled="">Seleccione el vuelo</option>
                        <option value="Santa Marta">Santa Marta</option>
                        <option value="Bogota">Bogota</option>
                        <option value="Medellin">Medellin</option>
                        <option value="Pereira">Pereira</option>
                    </select> 
                    <br><br><br><br><br><br><br><br>
                    <a class="button" href="https://www.google.com">EDITAR</a>
                </form>
            </div>
        
        {% else %}
            <form id="cpestana3"  class='form'>
                <p>
                <label class='caja2' for='name'>Ciudad de origen</label>
                <select class="select">
                    <option disabled="">Seleccionar ciudad de origen</option>
                    <option value="Santa Marta">Santa Marta</option>
                    <option value="Bogota">Bogota</option>
                    <option value="Medellin">Medellin</option>
                    <option value="Pereira">Pereira</option>
                </select>   
                
                <label class='caja2' for='name'>Ciudad de destino</label>
                <select class="select">
                    <option disabled="">Seleccionar ciudad destino</option>
                    <option value="Santa Marta">Santa Marta</option>
                    <option value="Bogota">Bogota</option>
                    <option value="Medellin">Medellin</option>
                    <option value="Pereira">Pereira</option>
                </select>   
                </p>

                <p>
                <label class='caja2' for='name'>Seleccionar Avion</label>
                <select class="select">
                    <option disabled="">Seleccionar Avion</option>
                    <option value="Santa Marta">Airbus A330</option>
                    <option value="Bogota">Airbus A321</option>
                    <option value="Medellin">Airbus A320</option>
                    <option value="Pereira">Airbus A319</option>
                </select> 
                <br><br><br><br><br><br>
                
                <label class='caja2' for='name'>Seleccionar Piloto</label>
                <select class="select">
                    <option disabled="">Selecciona el piloto</option>
                    <option value="Nancy Castellanos Torres">Nancy Castellanos Torres</option>
                    <option value="Fabian Beltran Bustos">Fabian Beltran Busto</option>
                    <option value="Heygler Garcia Castro">Heygler Garcia Castro</option>
                    <option value="Yezid Martinez Gomez">Yezid Martinez Gomez</option>
                </select> 
                </p>

                <label class='caja2' for='name'>Selecciona hora de salida</label>
                <select class="select">
                    <option disabled="">Selecciona la hora</option>
                    <option value="12:00">12:00</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                </select> 

                <input class="text-input" type="text" id="cupos" name="cupos" placeholder="Asignar cupos"/><br><br> 

                <br><br><br><br><br><br>
                <a class="button" href="https://www.google.com">EDITAR</a>
                <a class="button" href="https://www.google.com">ELIMINAR</a>
                                                            
            </form>  

        {% endif %}
        {% endblock content %}
    </div>
</body>
</html>



templates/Inicio.html
<html>

    <head>
        <title>Aeropuerto La Nubia</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/micss.css')}}" >
        <script src="{{ url_for('static', filename='js/site.js') }}"></script>
        
    </head>

    <body>

        <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
        <p class="avion">
            <img src="{{ url_for('static', filename='img/Avion2.jfif')}}" alt="imagen avion" width="1000" height="510"></div>
        </p>
        
        <div class="rectangulo"></div>

        </div> 
        <div class="piloto" >
            <a href="{{ url_for('main.login', tipo='Piloto') }}">
                <img class="circular--square" src="{{ url_for('static', filename='img/piloto.jpg')}}" alt="Pilotos" >
            </a>
            <p align="center">PILOTOS</p> 
        </div>         

        <div class="cliente">
            <a href="{{ url_for('main.login', tipo='Usuario') }}">
                <img class="circular--square" src="{{ url_for('static',filename='img/cliente.jfif')}}" alt="clientes">
            </a>
            <p align="center">CLIENTES</p>
        </div> 
       
        <div class="administrador">
            <a href="{{ url_for('main.login', tipo='Admin') }}">
                <img class="circular--square" src="{{ url_for('static',filename='img/corporativo.jpg')}}" alt="CORPORATIVO">
            </a>
            <p align="center">CORPORATIVO</p>
        </div>        

    </body>

</html>

templates/Login-wtf.html
<html>
    <head>
        <title>Iniciar Sesion {{tipo}}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/micss.css')}}" >
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/miocss.css')}}" >
        <script src="{{ url_for('static', filename='js/site.js') }}"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>

    <body>  
        <a href="{{ url_for('main.index') }}" method="GET">
            <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
        </a>
        <div class="rectangulo2"></div>

        <div>
            <img class="fondo" src="{{ url_for('static', filename='img/Fondo.jpeg')}}" alt="fondo de avion">
        </div>

        <p>
            <div class="formulario"></div>
            <div class="rectangulo3"><p align="center">INICIAR SESIÓN</p></div>
        </p>

        <form action= {{ url_for("main.dashboard", tipo=tipo) }} method="GET" class='form' >
            {{ form.hidden_tag() }}

            <div class="fuente">
                <p>
                    {{ form.correo.label}}
                    {{ form.correo(size=30, class_='text-input') }}
                </p>

                <p>
                    <div class="input-group">
                        {{ form.contraseña.label}}
                        <p onfocusout="validarcontraseña()">
                            {{ form.contraseña(size=51, class_='text-input') }}</p>
                        <div class="input-group-append">
                            <button id="show_password" class="btn btn-primary" type="button" onclick="mostrarClave();" >
                                <i id="icono" name="icono" class="fa fa-eye-slash"></i>
                            </button>
                        </div>
                    </div>
                </p>
                
                <p>
                    <div >
                        <a href="{{ url_for('main.restaurar_contraseña') }}" class="fuente2">Olvidaste tu contraseña</a>                         
                        {% if tipo == "Piloto" %}
                            <a align="left" class="fuente2" onclick="alertaPiloto();"></p> 
                        {% else %}
                            <p align="right">
                                <a href="{{ url_for('main.registro') }}" class="fuente2">Crear Cuenta</p>
                            </p>   
                        {% endif %}
                    </div>  
                </p>                  
                <p align="center">{{ form.iniciarsesion(class_='button') }}</p>
            </div>
        </form>        

    </body>
</html>

templates/Reservar.html
<!DOCTYPE html>
<html lang="sp">
<head>
<META charset="utf-8"/>
<link rel="stylesheet" type="text/css" media="screen" href="{{ url_for('static', filename='CSS/mioCSS.css') }}" />
<link rel="stylesheet" type="text/css" media="print"  href="{{ url_for('static', filename='CSS/print.css') }}" />

<script src="https://kit.fontawesome.com/d42f451a54.js" crossorigin="anonymous"></script>

<title>Reserva tu vuelo</title>

<link rel="shortcut icon" type="image/png" href="img/favicon.png"/>
</head>
<body>
  <a href="{{ url_for('main.index') }}" method="GET">
    <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
  </a>

  <div class="menu">
    <a href="{{ url_for('main.dashboard', tipo=tipo) }}">
    {% if tipo == "Admin" %}
        Agregar Vuelo
    {% else %}
        Dashboard {{ tipo }}</a>
    {% endif %}
    <a href="{{ url_for('main.consultaVuelo', tipo=tipo) }}">Consultar</a>
    
    {% if tipo == "Usuario" %}
      <a href="{{ url_for('main.reservaVuelo', tipo=tipo) }}">Reservar</a>
      <a href="{{ url_for('main.calificaVuelo', tipo=tipo) }}">Calificanos</a>
    {% endif %}
    
    <a href="{{ url_for('main.index') }}">Cerrar Sesion</a>
  </div>

  <div class="publicacion">
    <h3 class="caja">RESERVA TU VUELO</h3>
    <wrapper div id='wrapper'>
      <form action='' class='form'>
        <p class='field required half'>
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Origen' placeholder='Origen' required type='text'>
        </p>
        
        <p class='field required half'>
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Destino' placeholder='Destino' required type='text'>
        </p>

        <p align="center"></p>
        <p class='field required half'>
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Fecha salida' placeholder='Fecha salida' required type='text'>
        </p>
        
        
        <p class='field required half'>
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Fecha llegada' placeholder='Fecha llegada' required type='text'>
        </p>

        <p class='field'>
          <input class='button' type='submit' value='Consultar'>
        </p>

        <p class='field required half'>Código del vuelo
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Código del vuelo' required type='text'>
        </p>

        <p class='field required half'>Avión
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Avión' required type='text'>
        </p>
        
        <p align="center">
        <p class='field required half'>Capacidad
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Capacidad' required type='text'>
        </p>
      
        <p class='field required half'>Cupos Disponibles
          <label class='label required' for='name'></label>
          <input class='text-input' id='name' name='Cupos Disponibles' required type='text'>
        </p>
      
        <p class='field'>
          <input class='button' type='submit' value='Reservar'>
        </p>  
                
      </form>
    </wrapper>
  </div>
</body>
</html>

templates/RestablecerContraseña-wtf.html
<html>

    <head>
        <title>Restablecer Contraseña
            
        </title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/micss.css')}}" >

    </head>

    <body>
        <a href="{{ url_for('main.index') }}" method="GET">
            <img src="{{ url_for('static', filename='img/Logo.jpeg')}}" alt="0" width="320" height="100" >
        </a>
        <div class="rectangulo2"></div>

        <div>
            <img class="fondo" src="{{ url_for('static', filename='img/Fondo.jpeg')}}" alt="fondo de avion">
        </div>

        <div>
            <div class="formulario"></div>            
            <p align="center" class="titulo">Restablece tu Contraseña</p>
            <p class="subtitulo"></p>
            <p class="subtitulo">Ingresa solo uno de estos datos de identificación para recuperar tu acceso:</p> 
            <ul class="subtitulo" style="list-style-type: square">
                <li>E-mail registrado</li>
                <li>Número de Identificación</li>
            </ul>
        
        <form action= {{ url_for("main.login") }} method="POST">
            <div class="fuente">
                <p>
                    {{ form.dato.label }}
                    {{ form.dato(size=60) }}
                </p>
                <p>
                    {{ form.newContraseña.label }}
                    {{ form.newContraseña(size=60) }}
                </p>
                <p>
                    {{ form.newContraseña2.label }}
                    {{ form.newContraseña2(size=60) }}
                </p>
                
                <p class="subtitulo2">Tu contraseña necesita tener mínimo 8 caracteres, 
                    debe contener mínimo 1 mayúscula, 1 minúscula, 1 numero, y 1 carácter especial.</p>
                
                    <div class="button">
                        <p>{{ form.enviar() }}</p>
                    </div>  
                </div>
            </div>
        </form>
   
    </body>

</html>